### PR TITLE
Fix editor and console colors

### PR DESCRIPTION
**Pull request by svipas**
As title says.

image

Source editor

image

Console

image

### CODE REVIEW

**Comment by rmehri01** [comment]
Hey, thanks for this! 

I actually realized that the colors look a bit different even though I used the same hex values as the other themes. Maybe I should redo the colors but using the color picker instead? That seems to be more accurate

**Comment by svipas** [comment]
@rmehri01 You mean colors for the keywords, etc.? Here I fixed only editor background, selection, cursor, invisibles and current line. If they are seem a little bit off you can try to do a hack as a did:

image

I just grab "Red" slider and pull it in whatever location and then I update "Hex Color". I don't know why, but this way it works and it applies exact hex color, otherwise it uses a different color 😠

**Comment by rmehri01** [comment]
Yeah, I meant for the other colors too. Ah okay interesting, I must've been doing something wrong with the hex values. I'll merge this and update some of the other colors too then 😃

**Comment by svipas** [comment]
@rmehri01 Thanks, I appreciate it.

**Comment by rmehri01** [comment]
No problem! Thanks for the contribution. I think this is looking much better now:

Screenshot 2023-10-25 at 1 55 05 PM

**Comment by svipas** [comment]
It looks amazing ❤️

**Pull request merged**
